### ISSUE TITLE
Q2 PRO crashes w/ segmentation fault

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-quake2#32]
- fix the segmentation fault
- create a second test that uses q2pro

**Comment by JustinBenedick** [comment]
So last time we played q2 was in October 2021. I worked back then and there hasn't been any changes sense. Im thinking we bump the base version of debian back to what was the latest in October.

**Comment by dudleycodes** [comment]
@JustinBenedick that was my first though too - but if we could make it work with the latest version of Debian, that'd be nice.

Changes are the newer version of Debian dropped some dependency we need. Where's the list of the deps needed for q2pro?

**Comment by dudleycodes** [comment]
Either way, once we get it fixed we should definitely pin the Debian version instead of using `stable-slim`

**Comment by JustinBenedick** [comment]
Dependencies are listed here https://github.com/skullernet/q2pro/blob/master/INSTALL.md

build-essential libsdl2-dev libopenal-dev libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev libcurl4-gnutls-dev

Also the other option would be to update and recompile like I did last time.

**Comment by dudleycodes** [comment]
Has there been a new update to q2pro since we compiled and added it to the content server?

**Comment by dudleycodes** [comment]
> build-essential libsdl2-dev libopenal-dev libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev libcurl4-gnutls-dev

Those dependencies are what's needed to build it - do you know of a list of deps need just to run it?

**Comment by JustinBenedick** [comment]
Looking through the commits of q2pro since october I am not seeing anything significant for server stability
